// Auto-generated from a live scrape of https://odto.com/collections/collectibles
// — the Collectibles crate's pool.
// Prices converted from CAD to USD at the rate ODTO's own storefront
// quotes, then bucketed into rarity bands by price: eight items per
// band, lowest to highest, so a rarity step is always a price step.

export const PRIZE_POOL = [
  {
    name: "Supreme Longevity Soup Set",
    price: 125,
    rarity: "common",
    weight: 5.0,
    image: "assets/prizes/supreme-longevity-soup-set.jpeg",
    category: "collectibles",
  },
  {
    name: "Supreme Spin Skateboard Green",
    price: 132,
    rarity: "common",
    weight: 5.0,
    image: "assets/prizes/supreme-spin-skateboard-green.png",
    category: "collectibles",
  },
  {
    name: "Supreme Antihero Dog Skateboard Brown",
    price: 132,
    rarity: "common",
    weight: 5.0,
    image: "assets/prizes/supreme-antihero-dog-skateboard-brown.png",
    category: "collectibles",
  },
  {
    name: "Supreme Digi Skateboard Pink",
    price: 147,
    rarity: "common",
    weight: 5.0,
    image: "assets/prizes/supreme-digi-skateboard-pink.jpeg",
    category: "collectibles",
  },
  {
    name: "Supreme Inflatable Blimp",
    price: 147,
    rarity: "common",
    weight: 5.0,
    image: "assets/prizes/supreme-inflatable-blimp.png",
    category: "collectibles",
  },
  {
    name: "Supreme Ebony Zippo",
    price: 147,
    rarity: "common",
    weight: 5.0,
    image: "assets/prizes/supreme-ebony-zippo.png",
    category: "collectibles",
  },
  {
    name: "Bearbrick Sesame Street Elmo 400%",
    price: 147,
    rarity: "common",
    weight: 5.0,
    image: "assets/prizes/bearbrick-sesame-street-elmo-400.png",
    category: "collectibles",
  },
  {
    name: "KAWS Take, Share, Together Small Jigsaw Puzzle Set (100 Pieces)",
    price: 176,
    rarity: "common",
    weight: 5.0,
    image: "assets/prizes/kaws-take-share-together-small-jigsaw-puzzle-set-100-pieces.png",
    category: "collectibles",
  },
  {
    name: "Bearbrick BAPE Transformers Optimus Prime 200% Grey",
    price: 184,
    rarity: "uncommon",
    weight: 3.12,
    image: "assets/prizes/bearbrick-bape-transformers-optimus-prime-200-grey.jpeg",
    category: "collectibles",
  },
  {
    name: "POP Mart Labubu The Monster Let's Checkmate",
    price: 206,
    rarity: "uncommon",
    weight: 3.12,
    image: "assets/prizes/pop-mart-labubu-the-monster-let-s-checkmate.png",
    category: "collectibles",
  },
  {
    name: "Bearbrick Optimus Prime 100% & 400% Set",
    price: 220,
    rarity: "uncommon",
    weight: 3.12,
    image: "assets/prizes/bearbrick-optimus-prime-100-400-set.png",
    category: "collectibles",
  },
  {
    name: "Supreme Abstract Beach Towel Red",
    price: 220,
    rarity: "uncommon",
    weight: 3.12,
    image: "assets/prizes/supreme-abstract-beach-towel-red.jpeg",
    category: "collectibles",
  },
  {
    name: "Supreme Abstract Beach Towel Yellow",
    price: 220,
    rarity: "uncommon",
    weight: 3.12,
    image: "assets/prizes/supreme-abstract-beach-towel-yellow.jpeg",
    category: "collectibles",
  },
  {
    name: "Supreme Lezyne Cnc Bike Pump",
    price: 220,
    rarity: "uncommon",
    weight: 3.12,
    image: "assets/prizes/supreme-lezyne-cnc-bike-pump.jpeg",
    category: "collectibles",
  },
  {
    name: "Bearbrick Mickey Mouse BAPE 100% and 400% Set Green",
    price: 220,
    rarity: "uncommon",
    weight: 3.12,
    image: "assets/prizes/bearbrick-mickey-mouse-bape-100-and-400-set-green.png",
    category: "collectibles",
  },
  {
    name: "Bearbrick Mickey Mouse BAPE 100% and 400% Set Pink",
    price: 220,
    rarity: "uncommon",
    weight: 3.12,
    image: "assets/prizes/bearbrick-mickey-mouse-bape-100-and-400-set-pink.png",
    category: "collectibles",
  },
  {
    name: "Bearbrick Sex Pistols God Save The Queen 100% and 400% Set Clear",
    price: 220,
    rarity: "rare",
    weight: 1.88,
    image: "assets/prizes/bearbrick-sex-pistols-god-save-the-queen-100-and-400-set-clear.png",
    category: "collectibles",
  },
  {
    name: "Bearbrick Scarlet Spider 100% & 400% Set",
    price: 257,
    rarity: "rare",
    weight: 1.88,
    image: "assets/prizes/bearbrick-scarlet-spider-100-400-set.png",
    category: "collectibles",
  },
  {
    name: "Bearbrick Marvel Wolverine 400%",
    price: 257,
    rarity: "rare",
    weight: 1.88,
    image: "assets/prizes/bearbrick-marvel-wolverine-400.jpeg",
    category: "collectibles",
  },
  {
    name: "Bearbrick The L@st Spider-Man 400%",
    price: 257,
    rarity: "rare",
    weight: 1.88,
    image: "assets/prizes/bearbrick-the-l-st-spider-man-400.jpeg",
    category: "collectibles",
  },
  {
    name: "BAPE Kids 15th Anniversary ABC Camo Baby Milo Plush Yellow",
    price: 294,
    rarity: "rare",
    weight: 1.88,
    image: "assets/prizes/bape-kids-15th-anniversary-abc-camo-baby-milo-plush-yellow.png",
    category: "collectibles",
  },
  {
    name: "Bearbrick Carnage 100% & 400% Set",
    price: 294,
    rarity: "rare",
    weight: 1.88,
    image: "assets/prizes/bearbrick-carnage-100-400-set.jpeg",
    category: "collectibles",
  },
  {
    name: "Supreme Brick",
    price: 294,
    rarity: "rare",
    weight: 1.88,
    image: "assets/prizes/supreme-brick.jpeg",
    category: "collectibles",
  },
  {
    name: "Supreme Cordless Floodlight",
    price: 294,
    rarity: "rare",
    weight: 1.88,
    image: "assets/prizes/supreme-cordless-floodlight.jpeg",
    category: "collectibles",
  },
  {
    name: "Bearbrick Marvel Iron Man Mark 50 100% & 400% Set",
    price: 367,
    rarity: "epic",
    weight: 1.5,
    image: "assets/prizes/bearbrick-marvel-iron-man-mark-50-100-400-set.jpg",
    category: "collectibles",
  },
  {
    name: "BAPE Origaudio Bluetooth Speaker",
    price: 367,
    rarity: "epic",
    weight: 1.5,
    image: "assets/prizes/bape-origaudio-bluetooth-speaker.jpeg",
    category: "collectibles",
  },
  {
    name: "Bearbrick Iron Man Mark 7 400%",
    price: 404,
    rarity: "epic",
    weight: 1.5,
    image: "assets/prizes/bearbrick-iron-man-mark-7-400.png",
    category: "collectibles",
  },
  {
    name: "Supreme Wilson American Mini Football Brown",
    price: 404,
    rarity: "epic",
    weight: 1.5,
    image: "assets/prizes/supreme-wilson-american-mini-football-brown.png",
    category: "collectibles",
  },
  {
    name: "Supreme 20th Anniversary Skateboard",
    price: 440,
    rarity: "epic",
    weight: 1.5,
    image: "assets/prizes/supreme-20th-anniversary-skateboard.png",
    category: "collectibles",
  },
  {
    name: "Bearbrick Fantasia Mickey 1000%",
    price: 734,
    rarity: "epic",
    weight: 1.5,
    image: "assets/prizes/bearbrick-fantasia-mickey-1000.jpeg",
    category: "collectibles",
  },
  {
    name: "KAWS BFF Plush Black",
    price: 734,
    rarity: "epic",
    weight: 1.5,
    image: "assets/prizes/kaws-bff-plush-black.png",
    category: "collectibles",
  },
  {
    name: "KAWS Companion Open Edition Brown",
    price: 734,
    rarity: "epic",
    weight: 1.5,
    image: "assets/prizes/kaws-companion-open-edition-brown.jpeg",
    category: "collectibles",
  },
  {
    name: "KAWS Companion Plush Brown",
    price: 734,
    rarity: "legendary",
    weight: 1.0,
    image: "assets/prizes/kaws-companion-plush-brown.png",
    category: "collectibles",
  },
  {
    name: "KAWS Small Lie Open Edition Black",
    price: 734,
    rarity: "legendary",
    weight: 1.0,
    image: "assets/prizes/kaws-small-lie-open-edition-black.jpeg",
    category: "collectibles",
  },
  {
    name: "KAWS Small Lie Open Edition Brown",
    price: 734,
    rarity: "legendary",
    weight: 1.0,
    image: "assets/prizes/kaws-small-lie-open-edition-brown.jpeg",
    category: "collectibles",
  },
  {
    name: "Supreme The North Face Bandana Dolomite Sleeping Bag Red",
    price: 734,
    rarity: "legendary",
    weight: 1.0,
    image: "assets/prizes/supreme-the-north-face-bandana-dolomite-sleeping-bag-red.png",
    category: "collectibles",
  },
  {
    name: "KAWS Along The Way Open Edition Brown",
    price: 991,
    rarity: "legendary",
    weight: 1.0,
    image: "assets/prizes/kaws-along-the-way-open-edition-brown.jpeg",
    category: "collectibles",
  },
  {
    name: "Bearbrick BAPE Mickey Monotone 1000%",
    price: 1321,
    rarity: "legendary",
    weight: 1.0,
    image: "assets/prizes/bearbrick-bape-mickey-monotone-1000.jpeg",
    category: "collectibles",
  },
  {
    name: "Daniel Arsham Crystal Relic 002 Nintendo Game Boy Clear",
    price: 1468,
    rarity: "legendary",
    weight: 1.0,
    image: "assets/prizes/daniel-arsham-crystal-relic-002-nintendo-game-boy-clear.png",
    category: "collectibles",
  },
  {
    name: "Medicom Bearbrick 3125C Objective Edc 1000%",
    price: 2202,
    rarity: "legendary",
    weight: 1.0,
    image: "assets/prizes/medicom-bearbrick-3125c-objective-edc-1000.jpeg",
    category: "collectibles",
  },
];
