// Auto-generated from a live scrape of https://odto.com/collections/footwear
// — the Sneakers crate's pool.
// Prices converted from CAD to USD at the rate ODTO's own storefront
// quotes, then bucketed into rarity bands by price: eight items per
// band, lowest to highest, so a rarity step is always a price step.

export const PRIZE_POOL = [
  {
    name: "Nike Dunk Low GS Black White",
    price: 110,
    rarity: "common",
    weight: 5.0,
    image: "assets/prizes/nike-dunk-low-gs-black-white.jpeg",
    category: "sneakers",
  },
  {
    name: "Air Jordan 1 Mid GS Wear-Away",
    price: 117,
    rarity: "common",
    weight: 5.0,
    image: "assets/prizes/air-jordan-1-mid-gs-wear-away.jpeg",
    category: "sneakers",
  },
  {
    name: "Air Jordan 1 High GS Yellow Toe",
    price: 132,
    rarity: "common",
    weight: 5.0,
    image: "assets/prizes/air-jordan-1-high-gs-yellow-toe.jpeg",
    category: "sneakers",
  },
  {
    name: "Air Jordan 1 Low GS Green Toe",
    price: 132,
    rarity: "common",
    weight: 5.0,
    image: "assets/prizes/air-jordan-1-low-gs-green-toe.jpeg",
    category: "sneakers",
  },
  {
    name: "Adidas Ultra Boost 1.0 Highsnobiety [flawed - Size 8.5]",
    price: 147,
    rarity: "common",
    weight: 5.0,
    image: "assets/prizes/adidas-ultra-boost-1-0-highsnobiety-flawed-size-8-5.png",
    category: "sneakers",
  },
  {
    name: "Air Jordan 1 Mid WMNS Coconut Milk",
    price: 147,
    rarity: "common",
    weight: 5.0,
    image: "assets/prizes/air-jordan-1-mid-wmns-coconut-milk.jpeg",
    category: "sneakers",
  },
  {
    name: "Air Jordan 1 Low Reverse Bred",
    price: 154,
    rarity: "common",
    weight: 5.0,
    image: "assets/prizes/air-jordan-1-low-reverse-bred.jpeg",
    category: "sneakers",
  },
  {
    name: "Air Jordan 1 High Craft Vibrations Of Naija",
    price: 176,
    rarity: "common",
    weight: 5.0,
    image: "assets/prizes/air-jordan-1-high-craft-vibrations-of-naija.jpeg",
    category: "sneakers",
  },
  {
    name: "Yeezy Slide Slate Grey",
    price: 184,
    rarity: "uncommon",
    weight: 3.12,
    image: "assets/prizes/yeezy-slide-slate-grey.jpeg",
    category: "sneakers",
  },
  {
    name: "Air Jordan 1 Low GS Ice Blue",
    price: 184,
    rarity: "uncommon",
    weight: 3.12,
    image: "assets/prizes/air-jordan-1-low-gs-ice-blue.jpeg",
    category: "sneakers",
  },
  {
    name: "Yeezy Slide Infant Onyx",
    price: 184,
    rarity: "uncommon",
    weight: 3.12,
    image: "assets/prizes/yeezy-slide-infant-onyx.png",
    category: "sneakers",
  },
  {
    name: "Yeezy Slide Glow Green",
    price: 198,
    rarity: "uncommon",
    weight: 3.12,
    image: "assets/prizes/yeezy-slide-glow-green.jpeg",
    category: "sneakers",
  },
  {
    name: "Air Jordan 1 Low Shadow Toe",
    price: 206,
    rarity: "uncommon",
    weight: 3.12,
    image: "assets/prizes/air-jordan-1-low-shadow-toe.jpeg",
    category: "sneakers",
  },
  {
    name: "Yeezy Foam Runner Stone Salt",
    price: 220,
    rarity: "uncommon",
    weight: 3.12,
    image: "assets/prizes/yeezy-foam-runner-stone-salt.jpeg",
    category: "sneakers",
  },
  {
    name: "Nike Air Max 1 Blueprint",
    price: 220,
    rarity: "uncommon",
    weight: 3.12,
    image: "assets/prizes/nike-air-max-1-blueprint.jpeg",
    category: "sneakers",
  },
  {
    name: "Nike Dunk Low WMNS Rose Whisper",
    price: 235,
    rarity: "uncommon",
    weight: 3.12,
    image: "assets/prizes/nike-dunk-low-wmns-rose-whisper.jpeg",
    category: "sneakers",
  },
  {
    name: "Air Jordan 4 GS Thunder",
    price: 239,
    rarity: "rare",
    weight: 1.88,
    image: "assets/prizes/air-jordan-4-gs-thunder.jpeg",
    category: "sneakers",
  },
  {
    name: "Nike Air Force 1 Low Supreme Black White",
    price: 257,
    rarity: "rare",
    weight: 1.88,
    image: "assets/prizes/nike-air-force-1-low-supreme-black-white.png",
    category: "sneakers",
  },
  {
    name: "Air Jordan 1 Low Game Royal",
    price: 257,
    rarity: "rare",
    weight: 1.88,
    image: "assets/prizes/air-jordan-1-low-game-royal.jpeg",
    category: "sneakers",
  },
  {
    name: "Air Jordan 1 High Court Purple 2.0",
    price: 272,
    rarity: "rare",
    weight: 1.88,
    image: "assets/prizes/air-jordan-1-high-court-purple-2-0.jpeg",
    category: "sneakers",
  },
  {
    name: "Air Jordan 5 Fire Red",
    price: 279,
    rarity: "rare",
    weight: 1.88,
    image: "assets/prizes/air-jordan-5-fire-red.jpeg",
    category: "sneakers",
  },
  {
    name: "Air Jordan 4 Red Cement",
    price: 294,
    rarity: "rare",
    weight: 1.88,
    image: "assets/prizes/air-jordan-4-red-cement.jpeg",
    category: "sneakers",
  },
  {
    name: "Nike Kobe 8 Protro Halo",
    price: 294,
    rarity: "rare",
    weight: 1.88,
    image: "assets/prizes/nike-kobe-8-protro-halo.jpeg",
    category: "sneakers",
  },
  {
    name: "Air Jordan 1 Low Travis Scott Canary",
    price: 308,
    rarity: "rare",
    weight: 1.88,
    image: "assets/prizes/air-jordan-1-low-travis-scott-canary.png",
    category: "sneakers",
  },
  {
    name: "Air Jordan 4 Thunder",
    price: 330,
    rarity: "epic",
    weight: 1.5,
    image: "assets/prizes/air-jordan-4-thunder.jpeg",
    category: "sneakers",
  },
  {
    name: "Nike Ldv Waffle Sacai White Nylon",
    price: 330,
    rarity: "epic",
    weight: 1.5,
    image: "assets/prizes/nike-ldv-waffle-sacai-white-nylon.jpeg",
    category: "sneakers",
  },
  {
    name: "Yeezy Boost 700 Mauve",
    price: 330,
    rarity: "epic",
    weight: 1.5,
    image: "assets/prizes/yeezy-boost-700-mauve.jpeg",
    category: "sneakers",
  },
  {
    name: "Yeezy Boost 350 V2 Clay",
    price: 345,
    rarity: "epic",
    weight: 1.5,
    image: "assets/prizes/yeezy-boost-350-v2-clay.jpeg",
    category: "sneakers",
  },
  {
    name: "Yeezy Boost 350 V2 Black Static (non-Reflective)",
    price: 367,
    rarity: "epic",
    weight: 1.5,
    image: "assets/prizes/yeezy-boost-350-v2-black-static-non-reflective.jpeg",
    category: "sneakers",
  },
  {
    name: "Air Jordan 4 GS Black Canvas",
    price: 367,
    rarity: "epic",
    weight: 1.5,
    image: "assets/prizes/air-jordan-4-gs-black-canvas.jpeg",
    category: "sneakers",
  },
  {
    name: "Air Jordan 4 White Thunder",
    price: 404,
    rarity: "epic",
    weight: 1.5,
    image: "assets/prizes/air-jordan-4-white-thunder.png",
    category: "sneakers",
  },
  {
    name: "Air Jordan 1 High Dark Mocha",
    price: 440,
    rarity: "epic",
    weight: 1.5,
    image: "assets/prizes/air-jordan-1-high-dark-mocha.jpeg",
    category: "sneakers",
  },
  {
    name: "Air Jordan 1 High Lost And Found",
    price: 477,
    rarity: "legendary",
    weight: 1.0,
    image: "assets/prizes/air-jordan-1-high-lost-and-found.jpeg",
    category: "sneakers",
  },
  {
    name: "Air Jordan 4 Military Black",
    price: 514,
    rarity: "legendary",
    weight: 1.0,
    image: "assets/prizes/air-jordan-4-military-black.jpeg",
    category: "sneakers",
  },
  {
    name: "Air Jordan 1 Low Travis Scott Velvet Brown",
    price: 550,
    rarity: "legendary",
    weight: 1.0,
    image: "assets/prizes/air-jordan-1-low-travis-scott-velvet-brown.jpg",
    category: "sneakers",
  },
  {
    name: "Nike Air Force 1 Low Laser By Mark Smith",
    price: 587,
    rarity: "legendary",
    weight: 1.0,
    image: "assets/prizes/nike-air-force-1-low-laser-by-mark-smith.png",
    category: "sneakers",
  },
  {
    name: "Air Jordan 6 Travis Scott Medium Olive",
    price: 661,
    rarity: "legendary",
    weight: 1.0,
    image: "assets/prizes/air-jordan-6-travis-scott-medium-olive.jpeg",
    category: "sneakers",
  },
  {
    name: "Nike Air Vapormax Off-White Black",
    price: 918,
    rarity: "legendary",
    weight: 1.0,
    image: "assets/prizes/nike-air-vapormax-off-white-black.jpeg",
    category: "sneakers",
  },
  {
    name: "Nike Air Force 1 High Supreme White",
    price: 1174,
    rarity: "legendary",
    weight: 1.0,
    image: "assets/prizes/nike-air-force-1-high-supreme-white.png",
    category: "sneakers",
  },
  {
    name: "Nike SB Dunk Low Supreme Stars Hyper Royal",
    price: 1395,
    rarity: "legendary",
    weight: 1.0,
    image: "assets/prizes/nike-sb-dunk-low-supreme-stars-hyper-royal.jpeg",
    category: "sneakers",
  },
];
