// Auto-generated from a live scrape of https://odto.com/collections/apparel
// — the Streetwear crate's pool.
// Prices converted from CAD to USD at the rate ODTO's own storefront
// quotes, then bucketed into rarity bands by price: eight items per
// band, lowest to highest, so a rarity step is always a price step.

export const PRIZE_POOL = [
  {
    name: "Supreme Greetings Tee Red",
    price: 88,
    rarity: "common",
    weight: 5.0,
    image: "assets/prizes/supreme-greetings-tee-red.jpeg",
    category: "streetwear",
  },
  {
    name: "Essentials Jersey Crewneck Tee Black",
    price: 88,
    rarity: "common",
    weight: 5.0,
    image: "assets/prizes/essentials-jersey-crewneck-tee-black.png",
    category: "streetwear",
  },
  {
    name: "Supreme Mary 5 Panel Cap Yellow",
    price: 88,
    rarity: "common",
    weight: 5.0,
    image: "assets/prizes/supreme-mary-5-panel-cap-yellow.jpeg",
    category: "streetwear",
  },
  {
    name: "Supreme Blood Tee Black",
    price: 88,
    rarity: "common",
    weight: 5.0,
    image: "assets/prizes/supreme-blood-tee-black.png",
    category: "streetwear",
  },
  {
    name: "Supreme Bernadette Corporation Money Tee Purple",
    price: 88,
    rarity: "common",
    weight: 5.0,
    image: "assets/prizes/supreme-bernadette-corporation-money-tee-purple.jpg",
    category: "streetwear",
  },
  {
    name: "Stussy Smooth Stock Pigment Dyed Crewneck Guava",
    price: 103,
    rarity: "common",
    weight: 5.0,
    image: "assets/prizes/stussy-smooth-stock-pigment-dyed-crewneck-guava.png",
    category: "streetwear",
  },
  {
    name: "Supreme Christmas Tee White",
    price: 103,
    rarity: "common",
    weight: 5.0,
    image: "assets/prizes/supreme-christmas-tee-white.jpeg",
    category: "streetwear",
  },
  {
    name: "Essentials Back Logo Tee Harvest",
    price: 110,
    rarity: "common",
    weight: 5.0,
    image: "assets/prizes/essentials-back-logo-tee-harvest.jpeg",
    category: "streetwear",
  },
  {
    name: "Supreme Hooded Baseball Top Red",
    price: 110,
    rarity: "uncommon",
    weight: 3.12,
    image: "assets/prizes/supreme-hooded-baseball-top-red.png",
    category: "streetwear",
  },
  {
    name: "BAPE 1st Camo Crazy By Bathing Ape Tee Black",
    price: 110,
    rarity: "uncommon",
    weight: 3.12,
    image: "assets/prizes/bape-1st-camo-crazy-by-bathing-ape-tee-black.png",
    category: "streetwear",
  },
  {
    name: "Kith Marvel Galactus Vintage Tee Black",
    price: 132,
    rarity: "uncommon",
    weight: 3.12,
    image: "assets/prizes/kith-marvel-galactus-vintage-tee-black.png",
    category: "streetwear",
  },
  {
    name: "Supreme Obama Anorak Red",
    price: 147,
    rarity: "uncommon",
    weight: 3.12,
    image: "assets/prizes/supreme-obama-anorak-red.jpg",
    category: "streetwear",
  },
  {
    name: "Essentials Fw23 Hoodie Cloud Dance",
    price: 147,
    rarity: "uncommon",
    weight: 3.12,
    image: "assets/prizes/essentials-fw23-hoodie-cloud-dance.png",
    category: "streetwear",
  },
  {
    name: "Aime Leon Dore 86 Shorts Gold",
    price: 161,
    rarity: "uncommon",
    weight: 3.12,
    image: "assets/prizes/aime-leon-dore-86-shorts-gold.jpg",
    category: "streetwear",
  },
  {
    name: "Supreme Ss22 Antihero Hoodie Black",
    price: 176,
    rarity: "uncommon",
    weight: 3.12,
    image: "assets/prizes/supreme-ss22-antihero-hoodie-black.png",
    category: "streetwear",
  },
  {
    name: "Eric Emanuel Ee Basic Short Polka Dot Aqua Green",
    price: 184,
    rarity: "uncommon",
    weight: 3.12,
    image: "assets/prizes/eric-emanuel-ee-basic-short-polka-dot-aqua-green.png",
    category: "streetwear",
  },
  {
    name: "Eric Emanuel Ee Basic Short Red Paisley",
    price: 184,
    rarity: "rare",
    weight: 1.88,
    image: "assets/prizes/eric-emanuel-ee-basic-short-red-paisley.jpg",
    category: "streetwear",
  },
  {
    name: "Supreme Cherry Aqua Short Brown",
    price: 220,
    rarity: "rare",
    weight: 1.88,
    image: "assets/prizes/supreme-cherry-aqua-short-brown.jpeg",
    category: "streetwear",
  },
  {
    name: "Supreme Wrench Tee Orange",
    price: 220,
    rarity: "rare",
    weight: 1.88,
    image: "assets/prizes/supreme-wrench-tee-orange.jpeg",
    category: "streetwear",
  },
  {
    name: "Essentials Fw24 Heavy Fleece Full Zip Hoodie Crimson",
    price: 235,
    rarity: "rare",
    weight: 1.88,
    image: "assets/prizes/essentials-fw24-heavy-fleece-full-zip-hoodie-crimson.png",
    category: "streetwear",
  },
  {
    name: "Supreme Center Stripe Crewneck Royal",
    price: 257,
    rarity: "rare",
    weight: 1.88,
    image: "assets/prizes/supreme-center-stripe-crewneck-royal.jpeg",
    category: "streetwear",
  },
  {
    name: "Supreme Scarface Blimp Tee White",
    price: 257,
    rarity: "rare",
    weight: 1.88,
    image: "assets/prizes/supreme-scarface-blimp-tee-white.jpeg",
    category: "streetwear",
  },
  {
    name: "Supreme Levi's Roses Trucker Jacket Black",
    price: 294,
    rarity: "rare",
    weight: 1.88,
    image: "assets/prizes/supreme-levi-s-roses-trucker-jacket-black.jpeg",
    category: "streetwear",
  },
  {
    name: "Gallery Dept. Souvenir Tee White/black",
    price: 312,
    rarity: "rare",
    weight: 1.88,
    image: "assets/prizes/gallery-dept-souvenir-tee-white-black.jpeg",
    category: "streetwear",
  },
  {
    name: "Supreme Cnn The War Report Hoodie Navy",
    price: 330,
    rarity: "epic",
    weight: 1.5,
    image: "assets/prizes/supreme-cnn-the-war-report-hoodie-navy.jpeg",
    category: "streetwear",
  },
  {
    name: "Supreme Velvet Trucker Jacket Dusty Pink",
    price: 330,
    rarity: "epic",
    weight: 1.5,
    image: "assets/prizes/supreme-velvet-trucker-jacket-dusty-pink.jpeg",
    category: "streetwear",
  },
  {
    name: "Denim Tears Big Cotton Wreath Hoodie Purple",
    price: 352,
    rarity: "epic",
    weight: 1.5,
    image: "assets/prizes/denim-tears-big-cotton-wreath-hoodie-purple.png",
    category: "streetwear",
  },
  {
    name: "Supreme Gucci Mane Tee Grey",
    price: 367,
    rarity: "epic",
    weight: 1.5,
    image: "assets/prizes/supreme-gucci-mane-tee-grey.png",
    category: "streetwear",
  },
  {
    name: "Supreme Nas Tee White",
    price: 367,
    rarity: "epic",
    weight: 1.5,
    image: "assets/prizes/supreme-nas-tee-white.jpeg",
    category: "streetwear",
  },
  {
    name: "Supreme Astronaut Hoodie Burgundy",
    price: 367,
    rarity: "epic",
    weight: 1.5,
    image: "assets/prizes/supreme-astronaut-hoodie-burgundy.png",
    category: "streetwear",
  },
  {
    name: "Supreme Undercover Reversible Ma-1 Bomber Jacket Black",
    price: 367,
    rarity: "epic",
    weight: 1.5,
    image: "assets/prizes/supreme-undercover-reversible-ma-1-bomber-jacket-black.jpeg",
    category: "streetwear",
  },
  {
    name: "Supreme Field Hoodie Black",
    price: 404,
    rarity: "epic",
    weight: 1.5,
    image: "assets/prizes/supreme-field-hoodie-black.jpeg",
    category: "streetwear",
  },
  {
    name: "BAPE ABC Camo Tiger Full Zip Hoodie Green",
    price: 404,
    rarity: "legendary",
    weight: 1.0,
    image: "assets/prizes/bape-abc-camo-tiger-full-zip-hoodie-green.png",
    category: "streetwear",
  },
  {
    name: "BAPE Tiger Full Zip Hoodie Grey",
    price: 477,
    rarity: "legendary",
    weight: 1.0,
    image: "assets/prizes/bape-tiger-full-zip-hoodie-grey.png",
    category: "streetwear",
  },
  {
    name: "Supreme Comme Des Garcons Shirt Box Logo Tee Black",
    price: 565,
    rarity: "legendary",
    weight: 1.0,
    image: "assets/prizes/supreme-comme-des-garcons-shirt-box-logo-tee-black.jpeg",
    category: "streetwear",
  },
  {
    name: "Supreme Neil Young Tee Navy",
    price: 587,
    rarity: "legendary",
    weight: 1.0,
    image: "assets/prizes/supreme-neil-young-tee-navy.jpeg",
    category: "streetwear",
  },
  {
    name: "Supreme Box Logo Hoodie Sage (fw16)",
    price: 661,
    rarity: "legendary",
    weight: 1.0,
    image: "assets/prizes/supreme-box-logo-hoodie-sage-fw16.jpg",
    category: "streetwear",
  },
  {
    name: "Supreme Box Logo Crewneck Natural",
    price: 734,
    rarity: "legendary",
    weight: 1.0,
    image: "assets/prizes/supreme-box-logo-crewneck-natural.jpeg",
    category: "streetwear",
  },
  {
    name: "Supreme The North Face Statue Of Liberty Mountain Jacket Red",
    price: 881,
    rarity: "legendary",
    weight: 1.0,
    image: "assets/prizes/supreme-the-north-face-statue-of-liberty-mountain-jacket-red.jpeg",
    category: "streetwear",
  },
  {
    name: "Supreme The North Face Trans Antarctica Expedition Fleece Jacket Blue",
    price: 954,
    rarity: "legendary",
    weight: 1.0,
    image: "assets/prizes/supreme-the-north-face-trans-antarctica-expedition-fleece-jacket-blue.jpeg",
    category: "streetwear",
  },
];
