// Auto-generated from a live scrape of https://odto.com/collections/footwear
// (sorted by price, higher band) for the $250 tier.
// Prices converted from AED to USD (approx. peg) and bucketed into rarity
// tiers by price quintile within this pool.

export const PRIZE_POOL = [
  {
    name: "Air Jordan 1 Low '85 Royal",
    price: 154,
    rarity: "common",
    weight: 5.0,
    image: "assets/prizes/air-jordan-1-low-85-royal.png",
  },
  {
    name: "Yeezy Slide Slate Grey",
    price: 184,
    rarity: "common",
    weight: 5.0,
    image: "assets/prizes/yeezy-slide-slate-grey.jpeg",
  },
  {
    name: "Air Jordan 4 RM Sp Nigel Sylvester Driveway Grey",
    price: 235,
    rarity: "common",
    weight: 5.0,
    image: "assets/prizes/air-jordan-4-rm-sp-nigel-sylvester-driveway-grey.png",
  },
  {
    name: "Nike Air Max 95 Toronto",
    price: 257,
    rarity: "common",
    weight: 5.0,
    image: "assets/prizes/nike-air-max-95-toronto.png",
  },
  {
    name: "Air Jordan 4 Fear",
    price: 279,
    rarity: "common",
    weight: 5.0,
    image: "assets/prizes/air-jordan-4-fear.png",
  },
  {
    name: "Air Jordan 1 Low Travis Scott Canary",
    price: 308,
    rarity: "common",
    weight: 5.0,
    image: "assets/prizes/air-jordan-1-low-travis-scott-canary.png",
  },
  {
    name: "Air Jordan 4 Bred Reimagined",
    price: 352,
    rarity: "common",
    weight: 5.0,
    image: "assets/prizes/air-jordan-4-bred-reimagined.png",
  },
  {
    name: "Nike Kobe 6 Protro Dodgers",
    price: 367,
    rarity: "common",
    weight: 5.0,
    image: "assets/prizes/nike-kobe-6-protro-dodgers.png",
  },
  {
    name: "Yeezy Boost 350 V2 Cinder (Reflective)",
    price: 396,
    rarity: "uncommon",
    weight: 3.12,
    image: "assets/prizes/yeezy-boost-350-v2-cinder-reflective.jpeg",
  },
  {
    name: "New Balance 550 Aime Leon Dore Grey",
    price: 404,
    rarity: "uncommon",
    weight: 3.12,
    image: "assets/prizes/new-balance-550-aime-leon-dore-grey.jpeg",
  },
  {
    name: "New Balance 990V3 MIUSA KITH Steel Blue",
    price: 404,
    rarity: "uncommon",
    weight: 3.12,
    image: "assets/prizes/new-balance-990v3-miusa-kith-steel-blue.png",
  },
  {
    name: "Air Jordan 5 Awake NY Black",
    price: 404,
    rarity: "uncommon",
    weight: 3.12,
    image: "assets/prizes/air-jordan-5-awake-ny-black.png",
  },
  {
    name: "Air Jordan 3 J Balvin Rio",
    price: 426,
    rarity: "uncommon",
    weight: 3.12,
    image: "assets/prizes/air-jordan-3-j-balvin-rio.png",
  },
  {
    name: "Nike Air Foamposite Pro Wolf Grey",
    price: 440,
    rarity: "uncommon",
    weight: 3.12,
    image: "assets/prizes/nike-air-foamposite-pro-wolf-grey.png",
  },
  {
    name: "Yeezy Boost 350 V2 Copper",
    price: 440,
    rarity: "uncommon",
    weight: 3.12,
    image: "assets/prizes/yeezy-boost-350-v2-copper.jpeg",
  },
  {
    name: "Air Jordan 1 High Dark Mocha",
    price: 440,
    rarity: "uncommon",
    weight: 3.12,
    image: "assets/prizes/air-jordan-1-high-dark-mocha.jpeg",
  },
  {
    name: "Nike Kobe 6 Protro All Star",
    price: 477,
    rarity: "rare",
    weight: 1.88,
    image: "assets/prizes/nike-kobe-6-protro-all-star.png",
  },
  {
    name: "Air Jordan 6 Travis Scott Medium Olive",
    price: 477,
    rarity: "rare",
    weight: 1.88,
    image: "assets/prizes/air-jordan-6-travis-scott-medium-olive.jpeg",
  },
  {
    name: "Air Jordan 1 High GS Pine Green",
    price: 477,
    rarity: "rare",
    weight: 1.88,
    image: "assets/prizes/air-jordan-1-high-gs-pine-green.jpeg",
  },
  {
    name: "Nike SB Dunk Low Yuto Horigome",
    price: 492,
    rarity: "rare",
    weight: 1.88,
    image: "assets/prizes/nike-sb-dunk-low-yuto-horigome.png",
  },
  {
    name: "Nike Air Force 1 Low G-Dragon Para-Noise",
    price: 514,
    rarity: "rare",
    weight: 1.88,
    image: "assets/prizes/nike-air-force-1-low-g-dragon-para-noise.jpeg",
  },
  {
    name: "Air Jordan 1 Lance Mountain White",
    price: 514,
    rarity: "rare",
    weight: 1.88,
    image: "assets/prizes/air-jordan-1-lance-mountain-white.jpeg",
  },
  {
    name: "Nike Air Force 1 Low Clot Fragment Black Silk",
    price: 514,
    rarity: "rare",
    weight: 1.88,
    image: "assets/prizes/nike-air-force-1-low-clot-fragment-black-silk.jpeg",
  },
  {
    name: "Nike LDV Waffle Sacai Black Nylon",
    price: 550,
    rarity: "rare",
    weight: 1.88,
    image: "assets/prizes/nike-ldv-waffle-sacai-black-nylon.jpeg",
  },
  {
    name: "Nike Dunk Low Off-White University Red",
    price: 587,
    rarity: "epic",
    weight: 1.5,
    image: "assets/prizes/nike-dunk-low-off-white-university-red.jpeg",
  },
  {
    name: "Nike Air Foamposite One All Star Chromeposite",
    price: 587,
    rarity: "epic",
    weight: 1.5,
    image: "assets/prizes/nike-air-foamposite-one-all-star-chromeposite.jpeg",
  },
  {
    name: "Asics GT-2160 KITH Marvel Villains Green Goblin",
    price: 587,
    rarity: "epic",
    weight: 1.5,
    image: "assets/prizes/asics-gt-2160-kith-marvel-villains-green-goblin.png",
  },
  {
    name: "Nike Air Fear Of God 1 Oatmeal",
    price: 624,
    rarity: "epic",
    weight: 1.5,
    image: "assets/prizes/nike-air-fear-of-god-1-oatmeal.jpeg",
  },
  {
    name: "Asics Gel-Lyte III Ronnie Fieg Homage (Special Box)",
    price: 660,
    rarity: "epic",
    weight: 1.5,
    image: "assets/prizes/asics-gel-lyte-iii-ronnie-fieg-homage-special-box.jpeg",
  },
  {
    name: "Nike Air Max 1 Master",
    price: 734,
    rarity: "epic",
    weight: 1.5,
    image: "assets/prizes/nike-air-max-1-master.jpeg",
  },
  {
    name: "Nike Air Max 90 Atmos Duck Camo",
    price: 807,
    rarity: "epic",
    weight: 1.5,
    image: "assets/prizes/nike-air-max-90-atmos-duck-camo.jpeg",
  },
  {
    name: "Air Jordan 23 Trophy Room White",
    price: 881,
    rarity: "epic",
    weight: 1.5,
    image: "assets/prizes/air-jordan-23-trophy-room-white.png",
  },
  {
    name: "Chrome Hearts Horseshoe Slippers White",
    price: 881,
    rarity: "legendary",
    weight: 1.0,
    image: "assets/prizes/chrome-hearts-horseshoe-slippers-white.png",
  },
  {
    name: "Nike Blazer Mid Off-White All Hallows Eve",
    price: 954,
    rarity: "legendary",
    weight: 1.0,
    image: "assets/prizes/nike-blazer-mid-off-white-all-hallows-eve.jpeg",
  },
  {
    name: "Nike Air Force 1 Low Year Of The Dragon",
    price: 954,
    rarity: "legendary",
    weight: 1.0,
    image: "assets/prizes/nike-air-force-1-low-year-of-the-dragon.png",
  },
  {
    name: "Nike Air Force 1 Low Off-White Volt",
    price: 1174,
    rarity: "legendary",
    weight: 1.0,
    image: "assets/prizes/nike-air-force-1-low-off-white-volt.jpeg",
  },
  {
    name: "Air Jordan 1 Mid WMNS Digital Pink",
    price: 1174,
    rarity: "legendary",
    weight: 1.0,
    image: "assets/prizes/air-jordan-1-mid-wmns-digital-pink.jpeg",
  },
  {
    name: "Air Jordan 1 Low Travis Scott Fragment (2025)",
    price: 1321,
    rarity: "legendary",
    weight: 1.0,
    image: "assets/prizes/air-jordan-1-low-travis-scott-fragment-2025.jpg",
  },
  {
    name: "Nike Air Force 1 Low Clot 1World",
    price: 1321,
    rarity: "legendary",
    weight: 1.0,
    image: "assets/prizes/nike-air-force-1-low-clot-1world.jpeg",
  },
  {
    name: "Nike Air Max 97 Off-White OG",
    price: 1614,
    rarity: "legendary",
    weight: 1.0,
    image: "assets/prizes/nike-air-max-97-off-white-og.jpeg",
  },
];
