// Auto-generated from a live scrape of https://odto.com/collections/footwear
// (sorted by price, higher band) for the $1000 tier.
// Prices converted from AED to USD (approx. peg) and bucketed into rarity
// tiers by price quintile within this pool.

export const PRIZE_POOL = [
  {
    name: "Nike SB Dunk Low Tie Dye Raygun White",
    price: 550,
    rarity: "common",
    weight: 5.0,
    image: "assets/prizes/nike-sb-dunk-low-tie-dye-raygun-white.jpeg",
  },
  {
    name: "Nike Air Max 270 Travis Scott Cactus Trails",
    price: 550,
    rarity: "common",
    weight: 5.0,
    image: "assets/prizes/nike-air-max-270-travis-scott-cactus-trails.jpeg",
  },
  {
    name: "Air Jordan 1 High GS Dark Mocha",
    price: 565,
    rarity: "common",
    weight: 5.0,
    image: "assets/prizes/air-jordan-1-high-gs-dark-mocha.jpeg",
  },
  {
    name: "Nike Dunk Low Off-White University Red",
    price: 587,
    rarity: "common",
    weight: 5.0,
    image: "assets/prizes/nike-dunk-low-off-white-university-red.jpeg",
  },
  {
    name: "Nike Air Force 1 Low Laser By Mark Smith",
    price: 587,
    rarity: "common",
    weight: 5.0,
    image: "assets/prizes/nike-air-force-1-low-laser-by-mark-smith.png",
  },
  {
    name: "Air Jordan 4 A Ma Maniere",
    price: 587,
    rarity: "common",
    weight: 5.0,
    image: "assets/prizes/air-jordan-4-a-ma-maniere.jpeg",
  },
  {
    name: "Asics GT-2160 KITH Marvel Villains Green Goblin",
    price: 587,
    rarity: "common",
    weight: 5.0,
    image: "assets/prizes/asics-gt-2160-kith-marvel-villains-green-goblin.png",
  },
  {
    name: "Air Jordan 4 Nigel Sylvester Brick By Brick",
    price: 587,
    rarity: "common",
    weight: 5.0,
    image: "assets/prizes/air-jordan-4-nigel-sylvester-brick-by-brick.png",
  },
  {
    name: "Nike SB Dunk Low Grateful Dead Yellow Bear",
    price: 660,
    rarity: "uncommon",
    weight: 3.12,
    image: "assets/prizes/nike-sb-dunk-low-grateful-dead-yellow-bear.jpg",
  },
  {
    name: "Nike Kobe 1 Fade To Black",
    price: 660,
    rarity: "uncommon",
    weight: 3.12,
    image: "assets/prizes/nike-kobe-1-fade-to-black.jpeg",
  },
  {
    name: "Nike Air Max 90 Off-White Black",
    price: 734,
    rarity: "uncommon",
    weight: 3.12,
    image: "assets/prizes/nike-air-max-90-off-white-black.jpeg",
  },
  {
    name: "Air Jordan 1 High WMNS UNC Patent",
    price: 734,
    rarity: "uncommon",
    weight: 3.12,
    image: "assets/prizes/air-jordan-1-high-wmns-unc-patent.jpeg",
  },
  {
    name: "Nike Air Max 90 Atmos Duck Camo",
    price: 807,
    rarity: "uncommon",
    weight: 3.12,
    image: "assets/prizes/nike-air-max-90-atmos-duck-camo.jpeg",
  },
  {
    name: "Air Jordan 5 Awake Arctic Pink",
    price: 881,
    rarity: "uncommon",
    weight: 3.12,
    image: "assets/prizes/air-jordan-5-awake-arctic-pink.png",
  },
  {
    name: "Air Jordan 23 Trophy Room White",
    price: 881,
    rarity: "uncommon",
    weight: 3.12,
    image: "assets/prizes/air-jordan-23-trophy-room-white.png",
  },
  {
    name: "Air Jordan 1 High Trophy Room Chicago",
    price: 881,
    rarity: "uncommon",
    weight: 3.12,
    image: "assets/prizes/air-jordan-1-high-trophy-room-chicago.jpeg",
  },
  {
    name: "Nike Air Vapormax Off-White Black",
    price: 917,
    rarity: "rare",
    weight: 1.88,
    image: "assets/prizes/nike-air-vapormax-off-white-black.jpeg",
  },
  {
    name: "Air Jordan 23 Premier Titanium",
    price: 954,
    rarity: "rare",
    weight: 1.88,
    image: "assets/prizes/air-jordan-23-premier-titanium.jpeg",
  },
  {
    name: "Air Jordan 1 High Aleali May",
    price: 954,
    rarity: "rare",
    weight: 1.88,
    image: "assets/prizes/air-jordan-1-high-aleali-may.jpeg",
  },
  {
    name: "Nike Air More Uptempo Supreme Red",
    price: 1101,
    rarity: "rare",
    weight: 1.88,
    image: "assets/prizes/nike-air-more-uptempo-supreme-red.jpeg",
  },
  {
    name: "Nike Air Force 1 Low Off-White Volt",
    price: 1174,
    rarity: "rare",
    weight: 1.88,
    image: "assets/prizes/nike-air-force-1-low-off-white-volt.jpeg",
  },
  {
    name: "Nike Air Force 1 High Supreme Red",
    price: 1174,
    rarity: "rare",
    weight: 1.88,
    image: "assets/prizes/nike-air-force-1-high-supreme-red.png",
  },
  {
    name: "Air Jordan 1 High Union Black Toe",
    price: 1174,
    rarity: "rare",
    weight: 1.88,
    image: "assets/prizes/air-jordan-1-high-union-black-toe.jpeg",
  },
  {
    name: "Air Jordan 1 Low Travis Scott Fragment (2025)",
    price: 1321,
    rarity: "rare",
    weight: 1.88,
    image: "assets/prizes/air-jordan-1-low-travis-scott-fragment-2025.jpg",
  },
  {
    name: "Nike Air Force 1 Low Supreme CDG Shirt",
    price: 1321,
    rarity: "epic",
    weight: 1.5,
    image: "assets/prizes/nike-air-force-1-low-supreme-cdg-shirt.jpeg",
  },
  {
    name: "Air Jordan 1 Low Travis Scott Fragment",
    price: 1321,
    rarity: "epic",
    weight: 1.5,
    image: "assets/prizes/air-jordan-1-low-travis-scott-fragment.jpeg",
  },
  {
    name: "Nike Air Max 97 Off-White OG",
    price: 1614,
    rarity: "epic",
    weight: 1.5,
    image: "assets/prizes/nike-air-max-97-off-white-og.jpeg",
  },
  {
    name: "Air Jordan 1 Low Travis Scott Reverse Mocha",
    price: 1688,
    rarity: "epic",
    weight: 1.5,
    image: "assets/prizes/air-jordan-1-low-travis-scott-reverse-mocha.jpeg",
  },
  {
    name: "Nike SB Dunk Low Supreme Stars Mean Green",
    price: 1908,
    rarity: "epic",
    weight: 1.5,
    image: "assets/prizes/nike-sb-dunk-low-supreme-stars-mean-green.jpeg",
  },
  {
    name: "Air Jordan 1 High Off-White Chicago [Used - Size 9.5]",
    price: 2201,
    rarity: "epic",
    weight: 1.5,
    image: "assets/prizes/air-jordan-1-high-off-white-chicago-used-size-9-5.png",
  },
  {
    name: "Air Jordan 1 Low Travis Scott Mocha",
    price: 2201,
    rarity: "epic",
    weight: 1.5,
    image: "assets/prizes/air-jordan-1-low-travis-scott-mocha.jpeg",
  },
  {
    name: "Air Jordan 1 High Satin Royal",
    price: 2715,
    rarity: "epic",
    weight: 1.5,
    image: "assets/prizes/air-jordan-1-high-satin-royal.png",
  },
  {
    name: "Air Jordan 8 PE Oregon Ducks Gorge Green",
    price: 3302,
    rarity: "legendary",
    weight: 1.0,
    image: "assets/prizes/air-jordan-8-pe-oregon-ducks-gorge-green.jpeg",
  },
  {
    name: "Nike SB Blazer Mid Supreme White",
    price: 3669,
    rarity: "legendary",
    weight: 1.0,
    image: "assets/prizes/nike-sb-blazer-mid-supreme-white.png",
  },
  {
    name: "Nike Blazer SB Mid Supreme Black",
    price: 3669,
    rarity: "legendary",
    weight: 1.0,
    image: "assets/prizes/nike-blazer-sb-mid-supreme-black.png",
  },
  {
    name: "Air Jordan 8 OVO Calipari Pack Kentucky White",
    price: 4402,
    rarity: "legendary",
    weight: 1.0,
    image: "assets/prizes/air-jordan-8-ovo-calipari-pack-kentucky-white.png",
  },
  {
    name: "Air Jordan 1 High Off-White Chicago",
    price: 6236,
    rarity: "legendary",
    weight: 1.0,
    image: "assets/prizes/air-jordan-1-high-off-white-chicago.jpeg",
  },
  {
    name: "Adidas NMD Hu Pharrell Human Race Friends & Family Shock Pink",
    price: 7337,
    rarity: "legendary",
    weight: 1.0,
    image: "assets/prizes/adidas-nmd-hu-pharrell-human-race-friends-family-shock-pink.png",
  },
  {
    name: "Adidas NMD Hu Pharrell Human Race Friends & Family Burgundy",
    price: 10272,
    rarity: "legendary",
    weight: 1.0,
    image: "assets/prizes/adidas-nmd-hu-pharrell-human-race-friends-family-burgundy.png",
  },
  {
    name: "Nike SB Dunk Low Supreme Black Cement",
    price: 11005,
    rarity: "legendary",
    weight: 1.0,
    image: "assets/prizes/nike-sb-dunk-low-supreme-black-cement.jpeg",
  },
];
